### ISSUE TITLE
Question : How can i use this loader without attaching GraphQLDatabaseLoader with predefined TypeOrm connection in GQL config?

### ISSUE THREAD

**Issue by shajeeck** [Mando75/typeorm-graphql-loader#11]
I am running a few micro-services with multi tenancy (Database isolation) and central GraphQL server, hence TypeOrm connection is created on the fly after checking TenantId sent through GraphQL headers which happen from micro-service.

Is there anyway i can pass the gql args and info to these services and generate query builder from there instead of attaching GraphQLDatabaseLoader with predefined connection to context?

**Comment by Mando75** [comment]
Yes you could. If you wanted to, you can just initialize a new loader inside your resolver and/or service layer as long as it has access to the query info object. However, if you follow this approach you will lose most of the caching abilities the loader provides. The loader uses memoization to cache queries, so creating a new instance breaks that. Facebook's dataloader does something similar, so take a look at their docs if you want a more in-depth explanation https://github.com/graphql/dataloader#caching.  

I can take a look at adding in the ability to pass in a custom connection somewhere in the loader chain, but I feel like it may take some significant work.

**Comment by shajeeck** [comment]
Well, Facebook's dataloader is the approach i am using now with TypeOrm. 
A sample project for extracting Args and Fields ready for `where, select and pagination` to build queries using TypeOrm Repository `createQueryBuilder`  from the GraphQL at service level would be a great help, for a decoupled TypeOrm query builder from GraphQL

something like https://join-monster.readthedocs.io/

**Comment by Mando75** [comment]
I've looked into this a bit and adding the ability to submit a custom connection per query is going to interfere with some of the underlying queue logic that is used to cache/resolve queries. I only just finished refactoring most of the code-base and don't really have time to do it all over again at the moment. Perhaps down the line for a v2. 

without knowing a lot about your service layer implementation, my thought would be to just initialize a loader in each of your services on each request and either add it to your service context, or attach it to your request object. That way at least the caching will work on a per-service level. 

If you would like to see how this project extracts the fields and relations that need to be joined, see the [GraphQLInfoParser](https://github.com/Mando75/typeorm-graphql-loader/blob/master/src/lib/GraphQLInfoParser.ts) class.

I believe there are also packages out there that you can use to pull these things out of the info object. I chose to implement my own to prevent having to monitor another dependency.
