### ISSUE TITLE
Support Data Mapper entities

### ISSUE THREAD

**Issue by matthewtoschi** [Mando75/typeorm-graphql-loader#25]
Hi there,

Does this currently support typeorm entities following the Data Mapper approach? (not inheriting from BaseEntity).

Currently I get the following error for all of my entities:

```
Argument of type 'typeof MyEntity' is not assignable to parameter of type 'typeof BaseEntity'.
  Type 'typeof MyEntity' is missing the following properties from type 'typeof BaseEntity': useConnection, getRepository, target, hasId, and 19 more.
```

**Comment by Mando75** [comment]
It does not. The loader depends on properties from BaseEntity in order to load entity metadata for tables/columns when building the query.
