### ISSUE TITLE
Small fix for graphqlQueryBuilder.ts

### ISSUE THREAD

**Issue by coffeeforyou** [Mando75/typeorm-graphql-loader#4]
Hi,
it seems that the problem with TS choosing the wrong overload for 
`fields.reduce((o: Hash<Selection>, ast: FieldNode)...`
in graphqlQueryBuilder.ts can be resolved with 
`const fields = info.fieldNodes as Array<FieldNode>;`
instead of 
`const fields = info.fieldNodes;`

Congrats for the great project - I implemented the same functionality a while ago, but I like your version better.

**Comment by Mando75** [comment]
Thanks, I'll test it out. It was a rather annoying thing because tsc works fine, but ts-node was breaking during tests due to picking the wrong function signature.

**Comment by Mando75** [comment]
This is now fixed in the latest release. Thanks for the input!
